hypothesis:
    max_examples: 10
    
# Path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.2
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"